# Generated by Django 2.1.5 on 2019-03-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('product', '0089_auto_20190225_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='stores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='seller.Store'),
        ),
    ]
