# Generated by Django 2.1.7 on 2019-04-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0090_category_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='stores',
        ),
    ]
