# Generated by Django 2.1.7 on 2019-06-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_store_slug'),
        ('product', '0094_producttype_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_attributes', to='seller.Store'),
        ),
    ]
