# Generated by Django 2.1.7 on 2019-04-02 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
