# Generated by Django 2.1.7 on 2019-06-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_store_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='place_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
