# Generated by Django 2.1.7 on 2019-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_auto_20190130_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
