# Generated by Django 2.1.7 on 2019-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelogo',
            name='store',
        ),
        migrations.DeleteModel(
            name='StoreLogo',
        ),
    ]
