# Generated by Django 2.1.7 on 2019-04-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('menu', '0012_auto_20190104_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='seller.Store'),
        ),
    ]
