# Generated by Django 2.1.7 on 2019-05-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0071_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='shipping_type',
        ),
    ]
